output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks-cluster.kubeconfig
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "kong_domain" {
  description = "Access Kong Proxy"
  value       = "kong.${var.dns_base_domain}"
}

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks-cluster.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks-cluster.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks-cluster.cluster_security_group_id
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks-cluster.config_map_aws_auth
}