apiVersion: kuma.io/v1alpha1
kind: TrafficLog
metadata:
  name: log-all-traffic
mesh: default
spec:
  sources:
    - match:
        kuma.io/service: '*'
  destinations:
    - match:
        kuma.io/service: '*'
